services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 9090:80
    environment:
      PMA_ARBITRARY: 1

  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    ports: 
      - 3306:3306
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: sistema_ventas_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  sistema_ventas_back:
    build:
      context: ./sistema-ventas-back
    container_name: sistema_ventas_back
    ports:
      - 8080:3000
    depends_on:
      - mysql_db

  sistema_ventas_front:
    build:
      context: ./angular
    container_name: sistema_ventas_front
    ports:
      - 80:80
    depends_on:
      - sistema_ventas_back
    volumes:
      - /temp